services:
  #MANDATORY PART
  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html:ro
    healthcheck:
      test: ["CMD-SHELL", "curl -k -f https://localhost:443 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      wordpress:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - inception

  wordpress:
    build: ./requirements/wordpress
    expose:
      - "9000"
    env_file: .env
    secrets:
      - wp_admin_password
      - wp_user_password
      - db_password
      - db_root_password
    environment:
      WP_ADMIN_PASSWORD_FILE: /run/secrets/wp_admin_password
      WP_USER_PASSWORD_FILE: /run/secrets/wp_user_password
    volumes:
      - wordpress_data:/var/www/html
    healthcheck:
      test: ["CMD", "pgrep", "php-fpm83"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      mariadb:
        condition: service_healthy
      redis-cache:
        condition: service_started
    restart: unless-stopped
    networks:
      - inception

  mariadb:
    build: ./requirements/mariadb
    env_file: .env
    secrets:
      - db_root_password
      - db_password
      - wp_user_password
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$(cat /run/secrets/db_root_password) || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped
    networks:
      - inception
  #BONUS PART
  adminer:
    build: ./requirements/adminer
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      mariadb:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - inception

  static-site:
    build: ./requirements/static-site
    depends_on:
      wordpress:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - inception

  ftp-server:
    build: ./requirements/ftp-server
    env_file: .env
    secrets:
      - ftp_password
    environment:
      FTP_PASSWORD_FILE: /run/secrets/ftp_password
    volumes:
      - /home/daavril/data/wordpress/ftp_uploads:/var/www/html/ftp_uploads
    ports:
      - "21:21"
      - "30000-30010:30000-30010"
    depends_on:
      mariadb:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - inception

  redis-cache:
    build: ./requirements/redis-cache
    expose:
      - "6379"
    restart: unless-stopped
    networks:
      - inception

  uptime-kuma:
    build: ./requirements/uptime-kuma
    ports:
      - "3001:3001"
    restart: unless-stopped
    volumes:
      - uptime-kuma:/app/data
    networks:
      - inception


secrets:
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  ftp_password:
    file: ../secrets/ftp_password.txt

volumes:
  mariadb_data:
    name: srcs_mariadb_data
    driver: local
    driver_opts:
      type: none
      device: /home/daavril/data/mariadb
      o: bind

  wordpress_data:
    name: srcs_wordpress_data
    driver: local
    driver_opts:
      type: none
      device: /home/daavril/data/wordpress
      o: bind

  uptime-kuma:
    name: srcs_uptime-kuma
    driver: local
    driver_opts:
      type: none
      device: /home/daavril/data/uptime-kuma
      o: bind


networks:
  inception:
